# Generated by Django 4.2.16 on 2024-11-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
