# Generated by Django 4.2.16 on 2024-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
